version: "3.2"
services:
  manager:
    image: explabs/potee-manager
    build:
      context: .
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
